spring.application.name=workouttracker

spring.datasource.url= ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}
api.security.token.secret = ${DB_TOKEN_SECRET}
ninja.api.key=${NINJA_API_KEY}


spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true